# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Dasein and Interaction
email: daseintheworld@gmail.com
description: # this means to ignore newlines until "baseurl:"
  to be descripted for google search. included in header
# twitter_username: username
github_username: daseintheworld
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

github: [metadata]

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sein Park (박기범)"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software Engineer, Lazy Enthusiast, another dasein in this world"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://daseintheworld.github.io/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daseintheworld/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://daseintheworld.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daseintheworld/"
# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path
  
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: true
      toc: true
      sidebar:
        nav: "docs"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      

# subject_archive:
#   type: liquid
#   path: /subjects/
# tag_archive:
#   type: liquid
#   path: /tags/
